#开启rest风格
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #    static-path-pattern: /res/**
    #静态资源访问前缀 |-------|当前项目 + static-path-pattern + 静态资源名 = 静态资源文件夹下找
#  web:
#    resources:
#      static-locations: [classpath:/static_page/]

